language: go
go:
 - 1.2.2
 - 1.3rc2
services: mysql
before_install:
 - sudo apt-get update -qq && sudo apt-get install -qq libraptor2-dev libmagic-dev
before_script:
 - go get -t ./...
 
branches:
  only:
    - master
