stages:
  - build
  - deploy

variables:
  DEV_DOMAIN: "next.app.solidbase.info"
  PROD_DOMAIN: "app.solidbase.info"

build-dev:
  image: node:12
  stage: build
  only:
    - develop
  cache:
    key: node-modules
    paths:
      - node_modules/
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    VUE_APP_DOMAIN: https://$DEV_DOMAIN
  before_script:
    - npm install --progress=false
  script:
    - npm run build
  artifacts:
    paths:
      - dist

build-prod:
  image: node:12
  stage: build
  only:
    - master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    VUE_APP_DOMAIN: https://$PROD_DOMAIN
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - dist

deploy-dev:
  image: alpine
  stage: deploy
  only:
    - develop
  cache:
    key: none
    paths: []
  variables:
    NAME: "anonymous"
    EMAIL: "status@ecobytes.net"
  environment:
    name: development
    url: $DEV_DOMAIN
  script:
    - apk add --no-cache git openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - cd dist
    - git init
    - git add -A .
    - git commit -m runner
    - git remote add dokku dokku@dokku.ecobytes.net:$DEV_DOMAIN
    - git push -vv dokku +master

deploy-prod:
  image: alpine
  stage: deploy
  only:
    - master
  variables:
    NAME: "anonymous"
    EMAIL: "status@ecobytes.net"
  environment:
    name: production
    url: $PROD_DOMAIN
  script:
    - apk add --no-cache git openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - cd dist
    - git init
    - git add -A .
    - git commit -m runner
    - git remote add dokku dokku@dokku.ecobytes.net:$PROD_DOMAIN
    - git push -vv dokku +master
