apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "maddy.fullname" .}}
  labels: {{- include "maddy.labels" . | nindent 4}}
data:
  maddy.conf: |
{{ tpl (.Files.Get "files/maddy.conf") . | printf "%s" | indent 4 }}
  aliases: |
{{ tpl (.Files.Get "files/aliases") . | printf "%s" | indent 4 }}
